# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/',
                'doc_host': 'https://fastprogress.fast.ai',
                'git_url': 'https://github.com/fastai/fastprogress/tree/master/',
                'lib_path': 'fastprogress'},
  'syms': {'fastprogress.core': {}, 'fastprogress.fastprogress': {}, 'fastprogress.version': {}}}
